OrderService/Controllers/InStockController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OrderDatabase.Model;
using OrderRepository;
using System.Net.Http;

namespace OrderService.Controllers
{
    public class InStockController : Controller
    {
        private OrderDb db = new OrderDb();
        private IOrderRepository repository;

        //test product id
        private int productId = 1;

        public InStockController()
        {
            this.repository = new OrderRepo(new OrderDb());
        }

        // GET: InStock
        public ActionResult Index()
        {
            return View(db.Products.ToList());

            IEnumerable<OrderDatabase.Model.Product> o = null;
            HttpClient client = new HttpClient();
            client.BaseAddress = new System.Uri("http://localhost:52389/");
            client.DefaultRequestHeaders.Accept.ParseAdd("application/json");
            HttpResponseMessage response = client.GetAsync("/api/getproduct?productid=" + productId).Result;
            if (response.IsSuccessStatusCode)
            {
                o = response.Content.ReadAsAsync<IEnumerable<OrderDatabase.Model.Product>>().Result;


            }
            return View(o);
        }

       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OrderService/Controllers/OrderHistoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OrderDatabase.Model;
using System.Net.Http;
using OrderRepository;
using OrderService.Models;

namespace OrderService.Controllers
{
  

    public class OrderHistoryController : Controller
    {

        //test value
        private int userId = 1;
        
        private OrderDb db = new OrderDb();

        private IOrderRepository repository;

        public OrderHistoryController()
        {
            this.repository = new OrderRepo(new OrderDb());
        }

        

        // GET: OrderHistory
        public ActionResult Index()
        {
            //shows the order history for user 1

            IEnumerable<OrderDatabase.Model.Order> o = null;
            HttpClient client = new HttpClient();
            client.BaseAddress = new System.Uri("http://localhost:52389/");
            client.DefaultRequestHeaders.Accept.ParseAdd("application/json");
            HttpResponseMessage response = client.GetAsync("/api/getcustomerorder?userid=" + userId).Result;
            if (response.IsSuccessStatusCode)
            {
                o = response.Content.ReadAsAsync<IEnumerable<OrderDatabase.Model.Order>>().Result;

            }
            return View(o);
        }

        // GET: OrderHistory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OrderService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Thamco", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                    <li>@Html.ActionLink("Order History", "Index", "OrderHistory")</li>
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                    <li>@Html.ActionLink("Current In Stock Products", "Index", "InStock")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>